mutators:
  - type: mountPath
    from: /workspaces/catalog-service-node
    to: /Users/mikesir87/git/dockersamples/catalog-service-node
  - type: addLabels
    labels:
      com.mikesir87.example: test-value
  - type: remapImage
    from: nginx
    to: ghcr.io/mikesir87/nginx-mirror

responseFilters:
  - type: labelFilter
    requiredLabels:
      com.mikesir87.example: test-value

gates:
  - type: registry
    registries: ["docker.io", "ghcr.io"]
  - type: namespaceAllowlist
    namespaces: ["library", "mikesir87"]
  # - type: readonly
